name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Linting
        run: pnpm lint

      - name: Build
        run: pnpm build
